### ISSUE TITLE
Design issue on Crud Operation

### ISSUE THREAD

**Issue by Sana-Memon** [Sana-Memon/Grocery-Shop#5]
When we move to this page, https://localhost:44384/Allproducts/Index
here, the layout on this is null, but when i try to use admin dashboard layout, again its not working.
In views folder --> All Products --> Index
in above path, you'll see the 
"layout = null" and 
"layout = /Shared/ AdminDashboard"  --> this is commented, if i try to uncomment this, 
code will not work.

**Comment by Mubeen-hub** [comment]
Resolved
